build.sbt
project-manager/src/main/resources/application.conf
project-manager/src/main/scala/org/enso/projectmanager/RouteHelper.scala
project-manager/src/main/scala/org/enso/projectmanager/Server.scala
project-manager/src/main/scala/org/enso/projectmanager/api/Project.scala
project-manager/src/main/scala/org/enso/projectmanager/model/Project.scala
project-manager/src/main/scala/org/enso/projectmanager/services/ProjectsService.scala
project-manager/src/main/scala/org/enso/projectmanager/services/StorageManager.scala
project-manager/src/main/scala/org/enso/projectmanager/services/TutorialsDownloader.scala

Project Manager service. Responsible for creating and managing projects and tutorials from GH. In the future also responsible for opening projects and managing backends that currently have a project open, but that needs to wait until there's something that can work on a project (meaning, first @mwu-tow services). For now it can download tutorials, list projects and create projects.

Project manager

---

azure-pipelines.yml
interpreter/src/test/scala/org/enso/interpreter/FunctionArgumentsTest.scala

Currently test and benchmark steps in the CI pipeline do not stop the run on failure. This is desirable but led to builds being recognized by github as successful even if they shouldn't.
This PR adds additional step that fails the pipeline if there were issues encountered. 
It has been tested by f499f69 commit failing.

Fail CI build if there are issues

---

.github/PULL_REQUEST_TEMPLATE.md
doc/haskell-style-guide.md
doc/java-style-guide.md
doc/scala-style-guide.md

The style guides were unclear on the fact that we _want_ documentation comments for all relevant constructs. This clarifies the point across all of the style guides. 
This should ensure that this doesn't have to be asked for as often in code review as part of our 'definition of done'. 

Update Doc Comment Guidelines

---

doc/java-style-guide.md
doc/scala-style-guide.md

Fix Style Guides

---

Interpreter/src/bench/java/org/enso/interpreter/benchmarks/RecursionBenchmarks.java
Interpreter/src/bench/scala/org/enso/interpreter/RecursionFixtures.scala

Simple benchmark implemented as part of #25. Maybe it will prove useful in the future, there's no such thing as too many benchmarks.

this benchmark is pointless and that's the point

---

syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
syntax/definition/src/main/scala/org/enso/syntax/text/ParserDef.scala
syntax/specialization/src/test/scala/org/enso/syntax/text/Parser.scala

Adds support for single line comments, block comments, and code comments.

Parser: comment support.

---

azure-pipelines.yml
build.sbt

It bumps Graal.
Graal has beed bumped.

bump graal

---

lib/flexer/src/main/scala/org/enso/flexer/Parser.scala
syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
syntax/definition/src/main/scala/org/enso/syntax/text/ast/Repr.scala
syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builtin.scala
syntax/graph/src/main/scala/org/enso/syntax/graph/API.scala
syntax/graph/src/main/scala/org/enso/syntax/graph/DoubleRepresentation.scala
syntax/graph/src/main/scala/org/enso/syntax/graph/Main.scala
syntax/graph/src/test/scala/org/enso/syntax/graph/Tests.scala
syntax/specialization/src/main/scala/org/enso/syntax/text/Parser.scala
syntax/specialization/src/test/scala/org/enso/syntax/text/Parser.scala

Implements basic API for modification of textual representation
Although the parser doesn't need to reparse the whole file, it must reparse the top level blocks, since macro system can arbitrarily change nesting of the AST.

Parser Text API

---

Syntax/definition/src/main/scala/org/enso/syntax/text/AST2.scala
Syntax/definition/src/main/scala/org/enso/syntax/text/ast/Repr.scala
Syntax/definition/src/main/scala/org/enso/syntax/text/ast/text/Escape.scala
Syntax/definition/src/main/scala/org/enso/syntax/text/spec/ParserDef.scala
Syntax/specialization/src/bench/scala/org/enso/syntax/Parser.scala
Syntax/specialization/src/test/scala/org/enso/syntax/text/Parser.scala

Adds text literals and orphan blocks.

Merge cata-parser to cata-parser-merge.

---

Syntax/specialization/src/test/scala/org/enso/syntax/text/DocParserTests.scala

Adds Documentation Parser test suite to Enso, just uncommented commented out code which is already on master

Uncomment working & passing Doc Parser Tests

---

Syntax/graph/src/main/scala/org/enso/syntax/graph/API.scala
Syntax/graph/src/main/scala/org/enso/syntax/graph/DoubleRepresentation.scala
Syntax/graph/src/test/scala/org/enso/syntax/graph/Tests.scala

Notifcations for Graph and Text modifications.

Notifcations for Graph and Text modifications.

---

doc/java-style-guide.md
doc/rust-style-guide.md
doc/scala-style-guide.md

There was an informally-enforced rule around the complexity of lines of code that turns out to have not been written down in any of the style guides. This PR adds a small section regarding it to each of the guides where it matters. 
N/A

Update Style Guides Regarding Complexity

---

azure-pipelines.yml
build.sbt
engine/language-server/jupyter-kernel/enso/kernel.json
engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/LoopingCallOptimiserNode.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java

Sadly, still JDK 8.
Also we're not using the new loop nodes – they are slow.

Graal upgrade to 19.3.0

---

doc/design/syntax/syntax.md

Fixed some typos and improved the language of the design document a bit.
Please review before merging.

Language improvements in the design document

---

ide/README.md

Previously, paths in markdown links were incorrectly pointing to non-existent directories at repo root. This commit fixes them to link to existing subdirectories relative to the Readme file they're in.

ide/README: fix paths in markdown

---

build.sbt
common/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
engine/polyglot-api/src/main/java/org/enso/polyglot/MethodNames.java
engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
engine/polyglot-api/src/main/scala/org/enso/polyglot/Module.scala
engine/polyglot-api/src/main/scala/org/enso/polyglot/TopScope.scala
engine/polyglot-api/src/test/scala/org/enso/polyglot/ModuleManagementTest.scala
engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
engine/runtime/src/main/java/org/enso/interpreter/Language.java
engine/runtime/src/main/java/org/enso/interpreter/OptionsHelper.java
engine/runtime/src/main/java/org/enso/interpreter/node/ProgramRootNode.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/error/ModuleDoesNotExistException.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/PackageTest.scala

Adds operations required to implement the language server:
* Reparsing a module (useful when on-disk source file changes);
* Switching module to a source-literal representation and back;
* Creating new importable modules (for source files created after context initialization)
* Removing importable modules (for source files deletion after context initialization)
Nope.

Language Server files interface

---

build.sbt
common/graph/src/main/scala/org/enso/graph/Graph.scala
common/graph/src/main/scala/org/enso/graph/definition/Macro.scala
common/graph/src/test/scala/org/enso/graph/GraphTestDefinition.scala
engine/core-definition/src/main/scala/org/enso/core/CoreGraph.scala
engine/json-rpc-server/src/test/scala/org/enso/jsonrpcserver/MessageHandlerTest.scala
engine/runtime/src/main/scala/org/enso/compiler/Pass.scala
engine/runtime/src/main/scala/org/enso/compiler/core/Core.scala
engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/core/CorePrimTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/core/CoreTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/core/SmartConstructorsTest.scala

Adds some more in-depth tests for usage of the core graph. Closes #452.
Doesn't actually _finish_ the linked task, but due to plan changes it makes sense to PR what exists.

Core Tests

---

common/parser-service/src/main/scala/org/enso/ParserService.scala
common/parser-service/src/main/scala/org/enso/parserservice/Protocol.scala
common/syntax/specialization/js/src/main/scala/org/enso/syntax/text/Main.scala
common/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala

Pass id map to parser calls. 

---

doc/design/engine/engine-services.md
engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailure.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailureMapper.scala
engine/language-server/src/test/scala/org/enso/languageserver/WebSocketServerTest.scala
engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala

Reads the contents of a textual file.

File Reads for the Language Server

---

doc/design/engine/engine-services.md
engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemObject.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/Path.scala
engine/language-server/src/test/scala/org/enso/languageserver/WebSocketServerTest.scala
engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala

Creates filesystem objects, including any necessary but nonexistent parent directories.
It creates only files and directories.

File Creates for the Language Server

---

doc/design/engine/engine-services.md
engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileManagerTest.scala
engine/language-server/src/test/scala/org/enso/languageserver/websocket/WebSocketServerTest.scala

close #534 
- add `file/delete` message that asks the file manager to delete the specified file system object
- add tests
- update engine-services doc

Add file/delete message

---

azure-pipelines.yml

As the MacOS image on CI was expiring soon, this PR bumps the version on CI and also updates the Linux image at the same time. 
Closes #571 
N/A

Update CI Images

---

doc/design/engine/engine-services.md

Specifies the first messages in the execution API
Closes #445 
The issue of redirecting IO is ignored for now, should be handled with the visualizations API.

Execution API spec

---

doc/design/engine/engine-services.md
engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailure.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailureMapper.scala
engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileManagerTest.scala

close #535 
- add `file/copy` message that asks the file manager to copy the specified file system object
- add tests
- update engine-services doc

Add file/copy message to language server

---

README.md

This pull request updates readme to make it look like the one in IDE repo.
This PR is still a WIP

Update readme to make it consistent with one in IDE repository

---

CONTRIBUTING.md
README.md

fix a link in readme, change occurrences of Luna to Enso, move appropriate sections to contributing, fix links etc.

Further update of README.md and CONTRIBUTING.md

---

doc/design/syntax/syntax.md

Adds documentation to syntax.md about usage and syntax of Documentation Parser.

Add documentation for Documentation Parser

---

common/parser-service/src/main/scala/org/enso/ParserService.scala
common/parser-service/src/main/scala/org/enso/parserservice/Protocol.scala
common/syntax/specialization/js/src/main/scala/org/enso/syntax/text/Main.scala
common/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala

Fix parsing of metadata.

---

engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala

Force `FileManager` initialization before running the tests.

test: wait for FileManager initialization

---

.github/workflows/scala.yml

Actions on Master

---

.github/workflows/scala.yml

Fixes to the actions-based CI.
N/A

Artifact Builds on All Branches

---

CONTRIBUTING.md

- Added the requirement for a Java 8 version of Graal, as per [this issue](https://github.com/luna/enso/issues/618)
- Changed `runtime` to `runner` in the instructions for building the fat jar.

Fixes to CONTRIBUTING.md instructions

---

.github/workflows/scala.yml

This PR tweaks the cache keying on CI.

Another Attempt at Fixing Caching on CI

---

doc/language-server/specification/enso-protocol.md

From Capabilities to Execution Management

Move visualisationUpdate to more appropriate place

---

doc/runtime/implementation/polyglot/java.md
doc/runtime/implementation/polyglot/polyglot.md
doc/semantics/implementation/scoping.md
doc/semantics/specification/polyglot.md
doc/semantics/specification/polyglot/java.md
doc/semantics/specification/semantics.md
doc/syntax/specification/polyglot.md
doc/syntax/specification/syntax.md
doc/types/design/polyglot.md
doc/types/design/types.md

This PR updates the Enso design documentation with additional clarification performed by @mwu-tow. Additionally, it specifies elements of the polyglot syntax architecture for Enso.
Closes #685.
It doesn't incorporate the IDE-specific notes from Michał's document, but just the things that are relevant to the broader language design.

Design Doc Updates

---

.github/workflows/scala.yml
doc/language-server/specification/enso-protocol.md
engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/CreateHandler.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
engine/language-server/src/test/scala/org/enso/languageserver/websocket/rpc/ExecutionContextJsonMessages.scala
lib/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala

Covers all yesterday's remarks posted on Discord.
Changelog:
- update: init runtime
- doc: update `executionContext/create` 
- doc: update `executionContext/fork` 
- doc: complete `VisualisationConfiguration`
- doc: add example of Execution Context usage
`executionContext/create` API changed:
```typescript
{
contextId: ContextId;
canModify: CapabilityRegistration;
receivesUpdates: CapabilityRegistration;
}
```

Update Language Server Spec

---

engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintErrNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/ReadlnNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/system/NanoTimeNode.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/TextTest.scala
lib/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/ParserTest.scala

Needed for testing @lolczak's work.
Will need to be improved for the stdlib.

Implement `print_err` and `readln`

---

.github/settings.yml
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
docs/README.md
docs/language-server/README.md
docs/rfcs/0001-rfc-template.md
docs/rfcs/README.md

This PR fixes miscellaneous docs issues. 
Nope!

Miscellaneous Documentation Fixes

---

docs/runtime/caching.md

close #679
Changelog:
- doc: add runtime cache design

Add the Runtime Cache Design Docs

---

docs/syntax/comments.md
engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
engine/runtime/src/main/scala/org/enso/compiler/core/ir/MetadataStorage.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
engine/runtime/src/test/scala/org/enso/compiler/test/PassesTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/ComplexTypeTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/DocumentationCommentsTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CommentsTest.scala
lib/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/CommentRemover.scala
lib/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
lib/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/ParserTest.scala

Doc comments are handled nicely.
Disable comments are an abomination.

Handles disable and doc comments

---

.github/workflows/scala.yml
docs/CONTRIBUTING.md
engine/language-server/src/test/scala/org/enso/languageserver/filemanager/WatcherAdapterSpec.scala
project/build.properties

Closes #794
Change to latest sbt version to stay up to date.

Bump sbt version to 1.3.12

---

engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ThreadInterruptionTest.scala

Fixing Windows CI

---

docs/README.md
docs/syntax/types.md
docs/types/hierarchy.md

Clarify the Syntax for Type Operators

---

distribution/bin/enso.bat
distribution/bin/project-manager.bat

They were broken, they are fixed. Thanks @joenash for testing :)

Fix Launcher Scripts on Windows

---

.github/workflows/scala.yml

CI will now run for PRs into any branch, not just into master. 

Updates the CI Configuration to run for PRs into all Branches

---

.github/workflows/scala.yml
.gitignore
build.sbt
distribution/bin/enso
distribution/bin/enso.bat

Build independent distributions on the CI

---

.scalafmt.conf
engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala

The newest version of scalafmt allows automatic formatting of docstrings, so we're upgrading to it.

Update the Scalafmt Version

---

docs/README.md
docs/infrastructure/README.md
docs/infrastructure/java-11.md
docs/infrastructure/java11.md
docs/infrastructure/sbt.md

Describe infrastructure and Java 11 obstacles
