FileManager/src/test/scala/org/enso/filemanager/WatchTests.scala

Having shaky test is worse that not having test at all.
Disable the test, until it is properly investigated and either fixed or removed.
If accepted, I will rename the https://github.com/luna/enso/issues/73 issue.

Temporarily disable the shaky test.

---

lib/flexer/src/main/scala/org/enso/flexer/CodeGen.scala
lib/flexer/src/main/scala/org/enso/flexer/Group.scala
lib/flexer/src/main/scala/org/enso/flexer/NFA.scala
lib/flexer/src/main/scala/org/enso/flexer/ParserBase.scala
lib/flexer/src/main/scala/org/enso/flexer/State.scala
syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
syntax/definition/src/main/scala/org/enso/syntax/text/ParserDef.scala
syntax/specialization/src/bench/scala/org/enso/syntax/Parser.scala
syntax/specialization/src/main/scala/org/enso/syntax/text/Parser.scala
syntax/specialization/src/test/scala/org/enso/syntax/text/Parser.scala

Fixes rewind bug. Adds support for raw and multi-line strings.
Added `EOL(validIndent: Boolean)`, which signifies end of line. In case of multi line block `validIndent = false` when the next line is wrongly indented.

Support for raw and multi-line strings.

---

lib/flexer/src/main/scala/org/enso/flexer/Parser.scala
lib/flexer/src/main/scala/org/enso/flexer/spec/Macro.scala
syntax/definition/src/main/scala/org/enso/data/VectorMap.scala
syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
syntax/definition/src/main/scala/org/enso/syntax/text/ParserDef.scala
syntax/specialization/src/bench/scala/org/enso/syntax/Parser.scala
syntax/specialization/src/main/scala/org/enso/syntax/text/Parser.scala
syntax/specialization/src/test/scala/org/enso/syntax/text/Parser.scala

parser.run now takes `Seq([Int, Marker])` as additional input. During parsing if some AST token starts at offset associated with marker, it will be decorated as `Marked(token, marker)`.
Currently `Marker` only holds `Int` to make it testable.
VectorMap is a zipper-like vector for fast marker access.

Parser: Support Markers.

---

Interpreter/src/bench/scala/org/enso/interpreter/RegressionTest.scala
Interpreter/src/bench/scala/org/enso/interpreter/fixtures/RecursionFixtures.scala
Interpreter/src/main/java/org/enso/interpreter/Constants.java
Interpreter/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
Interpreter/src/main/java/org/enso/interpreter/node/callable/argument/sorter/ArgumentSorterNode.java
Interpreter/src/main/java/org/enso/interpreter/runtime/callable/argument/CallArgumentInfo.java
Interpreter/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
Interpreter/src/test/scala/org/enso/interpreter/InteropTest.scala
Interpreter/src/test/scala/org/enso/interpreter/LanguageTest.scala

This PR makes the interop library handle TCO and currying. No performance improvements were introduced and I stop to see room for some there – the calls are not getting hot enough to get compiled quickly. This however is an artificial issue for now – it only affects the speed of microbenchmarks and won't have impact on larger pure-enso projects. We may need to revisit this when the foreign languages interoperability is being implemented, though I doubt it will be the case.
Should be self explanatory

Interop Library Improvements

---

build.sbt
project/BenchTasks.scala
project/WithDebugCommand.scala

The easy debugging machinery can now be used with benchmark task.
Rather than implementing new logic for this, I've just changed the `runDebug` command to accept the task name as an argument. `runDebug` becomes `withDebug run`, while the new capability is `withDebug benchOnly`.

Add debugging capabilities to bench only

---

Interpreter/src/main/java/org/enso/interpreter/node/callable/argument/sorter/CachedArgumentSorterNode.java
Interpreter/src/test/scala/org/enso/interpreter/test/semantic/FunctionArgumentsTest.scala

Fixes an issue I've randomly stumbled upon when testing lazy arguments. Without this change, the test added here diverges.
Nothing important here. Amazingly enough, two benchmarks got a significant improvement, with no regressions elsewhere.

Fix lexical scope resolution in recursive calls

---

Syntax/definition/src/main/scala/org/enso/data/Pool.scala
Syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala

Stores identifiers in static pool to avoid bloating the memory with duplicate objects. Improves performance of benchmark `codeBlock with macros` by 30%.

AST Pool Implementation

---

azure-pipelines.yml
build.sbt
project/build.properties

This PR bumps the versions of GraalVM (to 19.2.1) and sbt (to 1.3.3) used for building Enso. 
It explicitly does _not_ bump the GraalVM API versions as there are no new packages available at this point in time. 

Bump SBT and GraalVM Versions

---

build.sbt

The magic I've introduced for incremental parser recompilations in the presence of scalac's "subpar" macro system was not triggering properly for the Test config. It does now.

Fix incremental compile for parser test env

---

Syntax/definition/src/main/scala/org/enso/syntax/text/spec/ParserDef.scala
Syntax/specialization/src/test/scala/org/enso/syntax/text/ParserTest.scala

Fixes parsing of `(+foo)`. The `(+` was parsed as an operator `(` with an incorrect suffix before that fix.

Fix Paren Operator Bug

---

Interpreter/src/main/java/org/enso/interpreter/builder/ExpressionFactory.java
Interpreter/src/main/java/org/enso/interpreter/node/ExpressionNode.java
Interpreter/src/main/java/org/enso/interpreter/node/expression/builtin/PrintNode.java
Interpreter/src/main/java/org/enso/interpreter/node/scope/AssignmentNode.java
Interpreter/src/main/java/org/enso/interpreter/runtime/Builtins.java
Interpreter/src/main/java/org/enso/interpreter/runtime/Context.java
Interpreter/src/main/java/org/enso/interpreter/runtime/Module.java
Interpreter/src/main/java/org/enso/interpreter/runtime/callable/function/ArgumentSchema.java
Interpreter/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
Interpreter/src/main/scala/org/enso/interpreter/Parser.scala
Interpreter/src/test/scala/org/enso/interpreter/test/semantic/LazyArgumentsTest.scala

Given we wan't to introduce more and more builtin functions and operators, it was about time to start properly handling builtin methods.
This cleans up the way builtin atoms were defined so far and makes the primitive print operator into a builtin function.
Not too many surprises here.

Better way of registering builtin functions

---

Pkg/src/main/resources/Main.enso
build.sbt

Fixes https://github.com/luna/enso/issues/261 – the native image of the interpreter failed on creating new projects, due to not being able to locate resources. This PR adds the relevant resources explicitly to the native image generation command.

Include relevant resources for native-image generation

---

build.sbt

Marks java sources as UTF-8 encoded. Without this compilation on Windows might fail, as javac defaults to default codepage, like:
```
sbt:enso> compile
[info] Compiling 1 Scala source and 83 Java sources to C:\dev\enso\Interpreter\target\scala-2.12\classes ...
[error] C:\dev\enso\Interpreter\src\main\java\org\enso\interpreter\node\callable\dispatch\LoopingCallOptimiserNode.java:14:1: unmappable character for encoding MS932
[error] C:\dev\enso\Interpreter\src\main\java\org\enso\interpreter\node\controlflow\MatchNode.java:54:1: unmappable character for encoding MS932
[error] (interpreter / Compile / compileIncremental) javac returned non-zero exit code
[error] Total time: 2 s, completed 2019-11-04 13:18:04
```

Set "-encoding UTF-8" for javac. 

---

Syntax/graph/src/main/scala/org/enso/syntax/graph/AstOps.scala
Syntax/graph/src/main/scala/org/enso/syntax/graph/DoubleRepresentation.scala
Syntax/graph/src/main/scala/org/enso/syntax/graph/SpanTree.scala
Syntax/graph/src/test/scala/org/enso/syntax/graph/Tests.scala

Implements listing enterable definitions in module's or definiton's scope, i.e. the getDefinitions API.

Graph API: definition discovery

---

Cargo.toml
common/rust/parser/Cargo.toml
common/rust/parser/src/api.rs
common/rust/parser/src/jsclient.rs
common/rust/parser/src/lib.rs
common/rust/parser/src/wsclient.rs
common/rust/prelude/Cargo.toml
common/rust/prelude/src/lib.rs

Indroduces `prelude` library, initially implemented in [basegl](https://github.com/luna/basegl) respository. @wdanilo says that this version is newer. 
Also, introduce `prelude` usage to `parser` library.
The library is expected to be used basically across our whole Rust codebase.
Part of work on #341.
Library name was changed to `prelude` (from `basegl-prelude`) and company e-mail was used in the package description.

Rust prelude library

---

common/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/DocParserDef.scala
common/scala/syntax/specialization/src/main/scala/org/enso/syntax/text/DocParser.scala
common/scala/syntax/specialization/src/main/scala/org/enso/syntax/text/DocParserStyle/style.sass
common/scala/syntax/specialization/src/main/scala/org/enso/syntax/text/Parser.scala
common/scala/syntax/specialization/src/test/scala/org/enso/syntax/text/DocParserTests.scala

In this Pull Request i've fixed parsing of lists, an error i've noticed just a while ago.
Thanks to that i've also got rid of any hardcoded values in parser.
I've also applied a quick change to html rendering process, now the file displays properly what it should display - first module name, then module documentation, and lastly module functions with theirs documentations.
Here you can see how an example file is rendered, please note that style isn't ready, i'll continue working on it in the next PR, as we're trying to keep pushing many small pr's.
Nothing important. quick fix.

Documentation Parser: Fix lists parsing, changes to HTML file rendering

---

common/scala/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
common/scala/syntax/specialization/src/main/scala/org/enso/syntax/text/Parser.scala

Introduces absolute AST positioning information to the parser. This is required for the interpreter to be able to display location info, even after macro resolution.
The way it works is:
1. The bare token stream is injected absolute info.
2. The constructors used by macro resolution are automagically injected with absolute position derivation logic.
3. The position of the toplevel of resolved macro is replaced with the position of the toplevel of the macro call, for perfect and unsurprising mapping.
1. The logic is not well tested here. I intend to do so end-to-end upon connecting to the interpreter, since I have much nicer capabilities to test it with Graal, without having to manually generate ginormous reference ASTs.

Absolute code locations

---

common/scala/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
engine/runtime/src/main/scala/org/enso/compiler/generate/AstToAstExpression.scala
engine/runtime/src/main/scala/org/enso/interpreter/Parser.scala

Adds source location info to old parser structures, for incorporation into the new-to-old translation passes.

Add source locations info to old parser

---

common/scala/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
common/scala/syntax/specialization/src/main/scala/org/enso/syntax/text/Parser.scala
engine/runtime/src/main/java/org/enso/interpreter/Language.java
engine/runtime/src/main/java/org/enso/interpreter/builder/ArgDefinitionFactory.java
engine/runtime/src/main/java/org/enso/interpreter/builder/CallArgFactory.java
engine/runtime/src/main/java/org/enso/interpreter/builder/ExpressionFactory.java
engine/runtime/src/main/java/org/enso/interpreter/builder/ModuleScopeExpressionFactory.java
engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/PanicNode.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
engine/runtime/src/main/scala/org/enso/compiler/core/OldAST.scala
engine/runtime/src/main/scala/org/enso/compiler/generate/AstToAstExpression.scala
engine/runtime/src/test/java/org/enso/interpreter/test/CodeLocationsTestInstrument.java
engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala

Truffle nodes are now marked with source locations. That means, instrumentation can use locations as ids, debuggers could attach breakpoints by lines and exceptions print usable stack traces.
Mostly trivial changes, the only "smart" bit is actually testing it. And the test harness used here actually serves as a PoC for the visualizations server ;)

Source location in Truffle nodes

---

common/rust/ast/core/Cargo.toml
common/rust/ast/core/src/lib.rs
common/rust/ast/macros/src/lib.rs
common/rust/parser/Cargo.toml
common/rust/parser/src/api.rs
common/rust/parser/src/jsclient.rs
common/rust/parser/src/lib.rs
common/rust/parser/src/wsclient.rs
common/rust/parser/tests/parsing.rs
common/scala/parser-service/src/main/scala/org/enso/parserservice/Protocol.scala
common/scala/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
common/scala/syntax/specialization/src/main/scala/org/enso/syntax/text/Parser.scala

This PR updates JSON serialization in Scala in Rust, so they are compatible, implementing #297.
Mostly path of least resistance was chosen. Serialized schema was slightly adjusted on both sides, so they work nicely together with manual code only for serialization top-level AST node. Working serialization has been confirmed for several simple types (identifiers, application) in semi-manual testing.
This does not mean that all types can be serialized — this PR fixes schema, however data structures still remain different between Scala and Rust, and this needs to be fixed before Scala/Rust interop is complete. This PR only made a few minor adjustments, to enable simple tests to pass.
The parser wrapper now uses the real AST in API. Still most of non-trivial use-cases will fail. Once #336 is …

Scala/Rust JSON serialization protocol unification

---

engine/runtime/src/main/java/org/enso/interpreter/instrument/ValueExtractorInstrument.java
engine/runtime/src/test/java/org/enso/interpreter/test/CodeLocationsTestInstrument.java
engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ValueExtractorTest.scala

A simple instrument allowing to observe and leak the values of selected expressions during program execution. Expressions are observed by their code position.
It is a very straightforward design, supported out of the box by Truffle's instrumentation.

Implement value extraction from scopes

---

doc/design/engine/caching-and-evaluation.md
doc/design/engine/function-call-flow.md

We had no concrete written-down design elements for the interpreter's caching mechanism, as well as no notes on how to deal with re-evaluation on function entry (via Enso Studio).
This document mentions only the points that have been discussed, and may need fleshing out some more in the future if we find unanswered questions.

Design Document for Caching and Re-Evaluation

---

doc/design/semantics/semantics.md

We had previously made assumptions about the return value of the `=` binding operator. These are now written into the documentation. 
This PR _purely_ codifies the assumptions made, and has no impact on _functionality_ of the existing interpreter codebase. It does, however, mean that the value returned by the `AssignmentNode` needs to be changed away from `Unit`.

Record Decisions About the Return Value of `=`

---

engine/runtime/src/main/java/org/enso/interpreter/instrument/ExactPositionListener.java
engine/runtime/src/main/java/org/enso/interpreter/instrument/FunctionCallExtractorInstrument.java
engine/runtime/src/main/java/org/enso/interpreter/instrument/ValueExtractorInstrument.java
engine/runtime/src/main/java/org/enso/interpreter/instrument/ValueOverrideInstrument.java
engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/IdeWorkflowTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ValueOverrideTest.scala

Introduces an instrument allowing to bypass execution of an arbitrary expression and return a fixed value instead.
Uses exceptions for trivial control flow, yay. That's the Graal API, I don't see any other way to do it.

Node value caching

---

build.sbt
common/graph/src/main/scala/org/enso/graph/Graph.scala
common/graph/src/main/scala/org/enso/graph/definition/Macro.scala
common/graph/src/test/scala/org/enso/graph/GraphTest.scala
common/graph/src/test/scala/org/enso/graph/GraphTestDefinition.scala
common/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/DocParserTests.scala
engine/core-definition/src/main/scala/org/enso/core/CoreGraph.scala
engine/runtime/src/main/scala/org/enso/compiler/core/Core.scala
engine/runtime/src/test/scala/org/enso/compiler/test/core/CorePrimTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/core/CoreTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/core/SmartConstructorsTest.scala

This PR adds smart constructors and other utilities that enable working fluently with the underlying core data structures. 
- More complex test cases are coming in the next PR as work under #452. This will also include benchmarks.
- The smart constructor tests rigorously test all of the expected properties of the smart constructors.
- This PR also fixes debug printing in the parser test suite as it was annoying me.

Core Smart Constructors

---

common/parser-service/src/main/scala/org/enso/ParserService.scala
common/parser-service/src/main/scala/org/enso/parserservice/Protocol.scala

Fix following the change from #556 — we accidently ended up having a JSON with a string with another serialized JSON.
Parser service takes request serialized as JSON. Request fields can be thusly fully typed, and don't need to consist `String` with another JSON. 
Tested against IDE's `wip/jv/idmap` branch.

Fixed Nested Serialization on the Parser Service Request Format

---

azure-pipelines.yml
build.sbt
engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
project/WithDebugCommand.scala

Closes #520.
The benchmark results for both v19 and v20 are very similar on my machine, besides a few highlighted exceptions. See the original (and very verbose) output logs [here.](https://gist.github.com/rzats/a40dd575ded344928f96eb5ad5d57526)
| Benchmark  | GraalVM 19.3.1 | GraalVM 20.0.0 |
| ------------- | ------------- | ------------- |
| AtomBenchmarks.benchGenerateList | 15.458242904915702  | 16.413785484116907 | 
| AtomBenchmarks.benchMapReverseCurryList | 22.969261846144597  | 21.243586123728388 |
| AtomBenchmarks.benchMapReverseList | 20.57017271427409  | 21.989881841025646  |
| ***AtomBenchmarks.benchReverseList*** | ***35.51495561110558***  | ***19.47601254844943***  |
| AtomBenchmarks.benchReverseListMethods | 20.97737287136907  | 19.92246298164083  |
| …

Update GraalVM to 20.0.0

---

.github/ISSUE_TEMPLATE/bug-report.md
azure-pipelines.yml
build.sbt
engine/runner/src/main/scala/org/enso/runner/Main.scala
project/BuildInfo.scala

This PR adds a `--version` CLI option to the runner project, which prints detailed information about the build and execution context of the enso binary. 
An example.
```
Enso Compiler and Runtime
Version:    0.0.1
Built with: scala-2.13.1 for GraalVM 20.0.0
Built from: wip/ara/better-version @ 1030864652f8f1e316ab3438f933f62f2806ebe4
Uncommitted changes, 1 commit on branch
Running on: Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.0.0, JDK 1.8.0_241-b07
Mac OS X 10.15.3 (x86_64)
```

Add a `--version` Flag for the CLI

---

engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala

Run GitHub Actions without the warmup hack.

Remove file manager warmup in tests

---

doc/design/engine/engine-services.md

Changelog:
- doc: fix `engine-services.md` indentation and wrap lines >80 characters

doc: fix engine-services.md format

---

engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
engine/runtime/src/main/java/org/enso/interpreter/Language.java
engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeServerInstrument.java
engine/runtime/src/main/java/org/enso/interpreter/node/callable/ApplicationNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/InvokeFunctionNode.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/Metadata.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ExpressionIdTest.scala

Introduces a truffle-side language service capable of performing on-demand code execution.
Couples the service with watcher instruments, enabling entering functions through call sites.
There's a bunch of test-only API messages, to be superseded by @4e6 's work on context stacks.

Language Execution Service

---

doc/design/engine/engine-services.md
engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
engine/language-server/src/main/scala/org/enso/languageserver/protocol/ClientController.scala
engine/language-server/src/main/scala/org/enso/languageserver/protocol/JsonRpc.scala
engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/PopHandler.scala
engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/PushHandler.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/MethodPointer.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeFailureMapper.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/StackItem.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/PopContextHandler.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/PushContextHandler.scala
engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
engine/language-server/src/test/scala/org/enso/languageserver/websocket/ContextRegistryTest.scala
engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
engine/runtime/src/main/scala/org/enso/interpeter/instrument/ExecutionContext.scala
engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ContextManagementTest.scala

closes: #588 
closes: #592
Changelog:
- add: executionContext/push
- add: executionContext/pop
- add: corresponding Push&Pop messages to runtime API
- add: support of the stack operations to the runtime `ExecutionContextManager`
Protocol extended with `EmptyStackError`, returned when popping an empty stack.
``` typescript
"error" : {
"code" : 2003,
"message" : "Stack is empty"
}
```

Add executionContext push & pop commands

---

engine/runtime/src/main/java/org/enso/interpreter/node/callable/MethodResolverNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/NumberBinaryOpMethod.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToTextNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/ConcatNode.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIR.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/TextTest.scala

Introduces 2 simple methods to the enso standard library. The only feasible part of the failed interpolated strings effort.
Allows to call methods on strings, which was previously impossible.

String concat and string conversion functions

---

engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ReadFileHandler.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
engine/language-server/src/main/scala/org/enso/languageserver/text/Buffer.scala
engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileNotificationsTest.scala
engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
engine/runtime/src/main/scala/org/enso/interpeter/instrument/ExecutionContext.scala
engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala

close #590 
Changelog:
- update: `CollaborativeBuffer` sends notifications to the runtime
- update: runtime re-executes expressions when a text change event is received
`Runtime.Api.CreateFileNotification` was removed. `Runtime.Api.OpenFileNotification` implies that the file already exists.

Execution Context Integration with Text Change Events

---

engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala

Fixes a bug where `this` argument of method calls was evaluated twice. No perf impact (except I can imagine a program that was exponential before and is linear now...).

Fix double-eval of this argument

---

.github/workflows/scala.yml

Such that the IDE team can easily depend on the schemas for the data protocol used by the engine, we upload these to S3 under the relevant commit hash such that they can get at them.
While we could split them out into a separate repo and use a submodule or subtree, these have significant problems of their own. 

Upload the FlatBuffers Schemas to S3

---

engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/NegateNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/NumberBinaryOpMethod.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LambdaShorthandArgsTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/OperatorSectionsTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/SimpleArithmeticTest.scala

This PR adds a hacky bit of support for unary minus as a right section of `-`. This does mean that we _can't_ right section `-`, but for now this is the best we can do.
Closes #717.
Users will be unable to write right sections of `-` for now. 

Add a Hack for Unary Minus

---

.github/workflows/docs.yml

This workflow updates the submodules in [luna.github.io](https://github.com/luna/luna.github.io) when there is a push to `docs`. The updated submodules are then pushed to the repo, [triggering a build of the site](https://github.com/luna/luna.github.io/actions/runs/108210889), causing the latest docs to be published. 

Add workflow to update `luna.github.io` on docs push

---

docs/syntax/README.md
engine/polyglot-api/src/main/java/org/enso/polyglot/MethodNames.java
engine/runtime/src/main/java/org/enso/interpreter/node/ClosureRootNode.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/FunctionBindingTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/GenerateMethodBodiesTest.scala
engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/OverloadsResolutionTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/FunctionSugarTest.scala

This PR introduces syntax sugar for the definition of functions and methods, in keeping with the language's syntax specification. It also fixes some potential bugs in the inline flow and with method body generation. 
Closes #496.
None of the miscellaneous code cleanups affect performance. 

Add Syntax Sugar for Defining Functions and Methods

---

build.sbt
docs/runtime/README.md
docs/runtime/instruments.md
project/FixInstrumentsGeneration.scala

Incremental compilation of instruments may lead to runtime errors when only some of the instruments are recompiled (because the unchanged instruments are not registered by the Annotation Processor).
To fix this, we add a task that ensures all instruments are recompiled when at least one of them changes.
The task fixing the issue assumes that all instruments have names ending in `Instrument` and reside in the `org.enso.interpreter.instrument` package. Those assertions are specified in the added documentation.

Add task fixing Instruments compilation.

---

.github/workflows/scala.yml
build.sbt
project/FixInstrumentsGeneration.scala

The old version did not take Language.java into account and it did not
trigger compilation on transitive dependencies.
Still did not find a way to safely re-trigger compilation, but a run
with inconsistent state is now aborted and a message is displayed to the
user to manually re-run the last task which will fix the inconsistency
problems.

Improve instrument compilation task

---

engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/AtomFixtures.scala
engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/NamedDefaultedArgumentFixtures.scala
engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/RecursionFixtures.scala
engine/runtime/src/main/java/org/enso/interpreter/instrument/ReplDebuggerInstrument.java
engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/callable/MethodResolverNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/BooleanBranchNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/AndNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/IfThenElseNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/NotNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/OrNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/ToTextNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/EqualsNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/ConstructorNode.java
engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/BreakpointNode.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Bool.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
engine/runtime/src/test/scala/org/enso/std/test/BooleanTest.scala
engine/runtime/src/test/scala/org/enso/std/test/NumberTest.scala

Introduces language-level support for boolean expressions. Benchmarks are the same as before. Closes #115 
Uses primitive booleans under the hood, but the exposed API is indistinguishable from standard Atoms. To that end, there's some cheating happening across different data-related nodes.

Booleans support
